# Generated by Django 5.1.3 on 2024-11-15 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': (('can_view_sales_opportunities', 'Can view sales opportunities'), ('can_manage_customers', 'Can manage customers'), ('can_create_interactions', 'Can create interactions'))},
        ),
    ]
